### ISSUE TITLE
oxford training/testing data availability?

### ISSUE THREAD

**Issue by aasharma90** [AAnoosheh/ToDayGAN#1]
Hi @AAnoosheh , 

Many thanks for publishing your code. I was wondering whether will it be possible for you to provide your training and testing datasets as well (Oxfod RobotCar)? Additionally, how about a pretrained model, just in case we'd like to test a few nighttime images? Thanks again!

[EDIT, 02/10/18]:
Actually, the datasets are not needed per se; just if you could provide us a similar script (like *datasets/download_dataset.sh) for dowloading Oxford data (if available on your server), that would be great. Or, if you could provide a list of images following the Oxford directory structure? Many thanks!

**Comment by AAnoosheh** [comment]
Hello, sorry Github started going into my Junk email folder for some reason recently!
Yes, I can provide access to a pretrained model - no problem. I'll do this in the next day or two.

For dataset, I don't know what is the best way to go about it. I could:
A. Provide lists of filenames (timestamps) which are universal identifiers for the RobotCars dataset. That way anyone can grab them from the official Oxford website themselves.
B. Upload them as zips, but then I don't know what the legal aspects of this are.
C. You could also grab any suitable selection of day (preferably cloudy not sunny) and night images form the Oxford site and train on them. It really just takes any 5k-10k images of any sort and it should be in the same quality range as ours.

**Comment by aasharma90** [comment]
Hi @AAnoosheh , 

Thanks again for your response! Yes, it will be great to have a pre-trained model, thank you for accommodating that request. 

Regarding the dataset, I personally think that (A) would be a better option. You can just release the names of the files, then it might not be difficult for others to get those files once they have downloaded the requisite datasets from the oxford website. And yes, I've already carried out (C), and the results look more or less similar to what you have reported in the paper. 

Just out of curiosity, did you also experiment with other translations, such as CITYSCAPES<->Oxford_NightTime, or KITTI<->Oxford_NightTime? Thanks again!

**Comment by AAnoosheh** [comment]
Here are two files containing the ids for the RobotCar files used for our training. The best model used left & right images from the same timestamps to boost training count as well.

[night.txt](https://github.com/AAnoosheh/ToDayGAN/files/2475359/night.txt)
[day.txt](https://github.com/AAnoosheh/ToDayGAN/files/2475360/day.txt)

I have not tried cross-dataset experiments, though I do know that artifacts tend to occur when using cameras with noticeably different image quality.

**Comment by AAnoosheh** [comment]
Also I updated the README with instructions and link for the pretrained model.
Cheers!

**Comment by aasharma90** [comment]
Thanks @AAnoosheh !
