### ISSUE TITLE
TodayGAN

### ISSUE THREAD

**Issue by VPRzhou** [AAnoosheh/ToDayGAN#13]
Hi,I have a doubt about the evaluation of ToDayGAN model.For I want to prove the generated images(night2day) have high quality and diversity.Have you use some metrics(IS、FID) to evaluate it?

**Comment by AAnoosheh** [comment]
Hi sorry I just saw this now.

I don't have any diversity metrics, and the images are deterministic per input.
So you cannot create a variety of outputs for a single input.
