### ISSUE TITLE
About the epochs in Training

### ISSUE THREAD

**Issue by seainlost81** [AAnoosheh/ToDayGAN#20]
Anoosheh, thank you for your work and provided code. I have a question about the epochs in the training. As stated in your article，training is run for 40 epochs. So, when we try to train a model as yours, the 'num_epochs_constant_LR' in 'python train.py --name <experiment_name> --dataroot ./datasets/<your_dataset> --n_domains <N> --niter <num_epochs_constant_LR> --niter_decay <num_epochs_decaying_LR>' is 20 or 40? Because when we use 20, the effect is not very satisfactory. Looking forward to your reply. Thanks in advance.
![1418235223450115_fake_0](https://user-images.githubusercontent.com/45096185/92506722-7304b480-f238-11ea-9b5d-06334203744e.png)
![1418235223450115_real_1](https://user-images.githubusercontent.com/45096185/92506725-75670e80-f238-11ea-8f5c-0d05797baa54.png)

**Comment by AAnoosheh** [comment]
Wow I totally forgot to update the number of epochs in the paper. I think I used to do 40 at first, and then for my final model I actually ran it for 150 (75+75) and then I didn't update the text.

**Comment by seainlost81** [comment]
Anoosheh, thank you for your prompt reply.
