### ISSUE TITLE
About turning the images flat from fisheye lenses

### ISSUE THREAD

**Issue by seainlost81** [AAnoosheh/ToDayGAN#21]
Anoosheh, sorry to disturb you again. How can I turn the images flat from fisheye lenses? In addition, the image looks like a grayscale image. How do we turn them into color images? Can you provide the corresponding python code to turn the images flat from fisheye lenses? Thanks in advance.

**Comment by AAnoosheh** [comment]
The Oxford dataset site provides that. I am not involved with the creation of that dataset, sorry.

Thanks

**Comment by seainlost81** [comment]
@AAnoosheh Thank you for your prompt reply.  In my option, the images we train should come from Bumblebee XB3 or Grasshopper2.  Using Bumblebee XB3, the trained image is as follows(Figure 1)
![1425062779308785](https://user-images.githubusercontent.com/45096185/93781200-b52bee00-fc5b-11ea-9778-61f42dea9e34.png)
When using Grasshopper2, the trained image is as follows(Figure 2)
![1425062779290556](https://user-images.githubusercontent.com/45096185/93781368-e5738c80-fc5b-11ea-8a50-d7b86cda86ea.png)
We want to know that you are training with images similar to Figure 1 or Figure 2.
In addition, their image formats are PNG, GRAYY8BPP.
Therefore, from a visual point of view, they like grayscale images.
We want to know whether they affect the training results.
Please forgive me for more problems.

**Comment by AAnoosheh** [comment]
Oh definitely from Grasshopper

**Comment by seainlost81** [comment]
@AAnoosheh  Thanks very much for your reply. As asked above, the trained images from Grasshopper seem to be grayscale images. Do they affect the training results？

**Comment by AAnoosheh** [comment]
I think you might be viewing them incorrectly. They look like the images on the README of this repo, in color.

**Comment by seainlost81** [comment]
@AAnoosheh  Thank you for your reply, I'll take a closer look. Thank you very much!
