### ISSUE TITLE
Could you please provide your trained model for night to day translation with UNIT in your paper?

### ISSUE THREAD

**Issue by seainlost81** [AAnoosheh/ToDayGAN#24]
Could you please provide your trained model for night to day translation with UNIT in your paper?
I need to compare test/train loss or accuracy. It'll be cool if you share that. 
My email address is liuhaibo81@gmail.com, thanks in advance.

**Comment by AAnoosheh** [comment]
Hi, I definitely don’t have this anymore as it was on the school servers, which were replaced soon after I graduated. 

Sorry about that. Though if you collect sufficient training data, it’s easy to run their model to train it.

**Comment by seainlost81** [comment]
Thank you for your prompt reply.
