### ISSUE TITLE
How to calculate the threshold accuracy based on the retrieved image ？

### ISSUE THREAD

**Issue by seainlost81** [AAnoosheh/ToDayGAN#25]
Dear AAnoosheh, thanks for your work. I have a question. I can utilize the NetVLAD to obtain the retrieved image, but I don‘t know how to calculate the threshold accuracy (I know the calculation formula). In other words, I don’t know how to get the location information of the query image and retrieved image. I think they should come from overcast-reference.db and query.db. However, I don't know how to use them. Thanks very much if you share that. My email address is liuhaibo81@gmail.com, thanks in advance.

**Comment by AAnoosheh** [comment]
Hi,

Yes it's confusing, I'll admit.  The dataset here is used: 
https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/RobotCar-Seasons/

The .txt files provide 6DOF matrix ground truth localizations.
I put a query image in (from either the _Night_ or _Night-rain_ image folders), convert to "daytime", find the closest image in the _Overcast_ folder, then compare the localization of the closest _Overcast_ image to that of the _Night_ query.

**Comment by seainlost81** [comment]
Thank you very much for your reply, I think I understand what you mean, thank you！
