### ISSUE TITLE
Training on Google Colab

### ISSUE THREAD

**Issue by iambankaratharva** [AAnoosheh/ToDayGAN#27]
Want to know where should I change the path such that it corresponds to my drive in the code. 
I've already tested car images on pre-trained model by changing the paths but am not able to figure out where i should make changes in path for saving the trained model?

**Comment by AAnoosheh** [comment]
Hi, I have very little experience with Colab, and have never done anything relating to custom paths there.

But this is where saving is done in my code:   
https://github.com/AAnoosheh/ToDayGAN/blob/12de3af4f209cd227bdc54160fc3164f97f6732d/models/base_model.py#L42

... and that in turn calls this function to save each network individually in pieces:  
https://github.com/AAnoosheh/ToDayGAN/blob/12de3af4f209cd227bdc54160fc3164f97f6732d/models/networks.py#L333

**Comment by iambankaratharva** [comment]
!python /content/drive/MyDrive/ToDayGAN/train.py --continue_train --which_epoch 75 --name cars --checkpoints_dir /content/drive/MyDrive/ToDayGAN/checkpoints --dataroot /content/drive/MyDrive/ToDayGAN/datasets/d2n --n_domains 2 --niter 100 --niter_decay 0 --save_epoch_freq 25
