### ISSUE TITLE
Training and testing using CULane?

### ISSUE THREAD

**Issue by paopao-long** [AAnoosheh/ToDayGAN#29]
Hi Asha, I'm sorry to bother you!I try to use ToDayGAN for training and testing CULane.But I got very strange results. I don't know why.
The real night image is :
![06032146_0955_00630_real_1](https://user-images.githubusercontent.com/59524741/137246315-66a62b3d-c100-4871-bbc3-ece2978fbd82.png)
Night image translated to day:
![06032146_0955_00630_fake_0](https://user-images.githubusercontent.com/59524741/137246802-c47baf89-1c9c-4a74-add8-901b6487134a.png)

**Comment by AAnoosheh** [comment]
Hi,

this is not an unimaginable scenario. Could be you beed more data to train. 

I would also try adding a —lambda-forward loss modifier option of something small like 0.2 or so.
