### ISSUE TITLE
Lack of DenseVLAD part of localization

### ISSUE THREAD

**Issue by hmf21** [AAnoosheh/ToDayGAN#32]
Thanks for your sharing this impressive work, but it looks only contain the ToDayGAN part and what about the localization part? 
Could you share about the DenseVLAD featurization and the details of its implementation?

**Comment by AAnoosheh** [comment]
Hi yes, you can find all the other resources on the main challenge repo here:

https://github.com/tsattler/visuallocalizationbenchmark

**Comment by hmf21** [comment]
Hi @AAnoosheh thanks for your rapid reply.
Unfortunately, I found that the project homepage of DenseVLAD is not accessible any more and there is also rare implement details about it at Github. So I am wondering may be you have some code resource about the DenseVLAD.
Whatever, thanks for your reply~

**Comment by AAnoosheh** [comment]
Oh no, it appears DenseVLAD has fallen off the face of the earth!

I can't find any site or even repo with it

**Comment by AAnoosheh** [comment]
The code was on my school computer from many years ago, so I don't have even that.

You could try messaging the owner of the other repo (Professor Torsten Sattler) to see if he might have a copy left on his disk somewhere

**Comment by hmf21** [comment]
Hahh, this has indeed disappeared from the Internet. Many benchmark shows this tranditional method can achieve comparable performance than these learning-based algorithm, therefore I search for this repo, however I found nothing.
Anyway it is great appreciate for your reply and your impressive work!
