### ISSUE TITLE
About the discriminator

### ISSUE THREAD

**Issue by ArcherrrrR** [AAnoosheh/ToDayGAN#4]
Hello, I have just read your paper and try to run your code. For the three discriminators, you mention in the paper that the loss are averaged in the end equally  And I want to know what should I change in the code if I want to put more weight on the gradient discriminator. For I am just a new hand in coding and don't know how to do it. Hope you can help me! Thanks a lot!

**Comment by AAnoosheh** [comment]
Hi, 

Line 45 of combogan_model.py contains the averaging you are looking for.
The order of the three losses in there are RGB, Gray, and Gradients, respectively, so you can change the weighting as you need.

Note that I have tried 0.25,0.25,0.5 in the past and got significantly worse results.
