### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by pmwenzel** [AAnoosheh/ToDayGAN#8]
Do you also provide a pretrained model for robotcar_2night, which translates from day to night images? Thanks

**Comment by AAnoosheh** [comment]
Hi,

Each model always can do both directions, since that is integral to how it's trained. 

But trust me, you don't want to go from day to night. It's not pretty...

**Comment by pmwenzel** [comment]
I assumed the same since this is the logic CycleGANs are being trained. However, why do you think the way from day to night is so much worse than from night to day?

**Comment by AAnoosheh** [comment]
The night images from RobotCar are plagued with speckle nosie, compression-y artifacts, as well as this weird blue bounceback noise from the car's Lidar. Thus fake night images generated are super artifacty and ugly.
